# Build the quickfix Python extension from this checkout with `pip install .` -- no autotools, no
# SWIG run, no out-of-tree source assembly.
#
# Upstream publishes the PyPI package from a tree it assembles by hand, so the repository itself
# has never been pip-installable. This mirrors that package's setup.py against the repository
# layout, and differs from it in two deliberate ways:
#   - TLS is on. The PyPI build defines neither HAVE_SSL nor the OpenSSL link, so its
#     SSLSocketInitiator throws ConfigError("HAVE_SSL not enabled") at construction.
#   - OpenSSL is linked through `libraries=`, which puts -lssl -lcrypto AFTER the objects. Passing
#     them in LDFLAGS puts them before, and GNU ld's --as-needed (Debian's default) then drops
#     them: the build succeeds and the extension fails to import with "undefined symbol: BN_...".
# The two headers ./configure would generate are written under build/ rather than committed.
import glob
import os
import pathlib

from setuptools import Extension, setup
from setuptools.command.build_ext import build_ext

SOURCE_DIRECTORY = "src/C++"
SWIG_DIRECTORY = "src/swig"
PYTHON_DIRECTORY = "src/python"
GENERATED_INCLUDE_DIRECTORY = pathlib.Path("build") / "generated"
# Windows precompiled-header stub; it includes a config.h that only the Windows build has.
WINDOWS_ONLY_SOURCES = {"stdafx.cpp"}
SWIG_GENERATED_SOURCE = f"{PYTHON_DIRECTORY}/QuickfixPython.cpp"

# Where OpenSSL lives when it is not on the default search path: Homebrew on Apple silicon, then
# Homebrew on Intel. Debian's libssl-dev needs no entry. A prefix that does not exist is skipped,
# so one list serves every platform. QUICKFIX_OPENSSL_PREFIX names any other installation.
OPENSSL_PREFIX_CANDIDATES = [
    os.environ.get("QUICKFIX_OPENSSL_PREFIX", ""),
    "/opt/homebrew/opt/openssl@3",
    "/usr/local/opt/openssl@3",
]

# What ./configure writes into config_unix.h on the hosts this is built for (glibc and macOS),
# taken from the 1.16.0 PyPI package. Allocator.h is the same package's "no custom allocator" form.
CONFIG_UNIX_H = """/* Generated by setup.py. Do not edit; see CONFIG_UNIX_H there. */
#define GETHOSTBYNAME_R_INPUTS_RESULT 1
#define HAVE_CLOCK_GETTIME 1
#define HAVE_CXX11 1
#define HAVE_CXX14 1
#define HAVE_CXX17 1
#define HAVE_DLFCN_H 1
#define HAVE_FTIME 1
#define HAVE_INTTYPES_H 1
#define HAVE_LIBPTHREAD 1
#define HAVE_STDINT_H 1
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define SELECT_MODIFIES_TIMEVAL 1
#define STDC_HEADERS 1
#define TERMINATE_IN_STD 1
#define TYPEINFO_IN_STD 1
#define VERSION "1.16.0"
#define _REENTRANT 1
"""
ALLOCATOR_H = "/* Generated by setup.py: no custom allocator. */\n"

# The PyPI package's flags, unchanged.
EXTRA_COMPILE_ARGS = [
    "-std=c++17",
    "-Wno-deprecated",
    "-Wno-unused-variable",
    "-Wno-unused-label",
    "-Wno-deprecated-declarations",
    "-Wno-maybe-uninitialized",
    "-D__cpp_noexcept_function_type",
]


def write_generated_headers() -> str:
    GENERATED_INCLUDE_DIRECTORY.mkdir(parents=True, exist_ok=True)
    (GENERATED_INCLUDE_DIRECTORY / "config_unix.h").write_text(CONFIG_UNIX_H)
    (GENERATED_INCLUDE_DIRECTORY / "Allocator.h").write_text(ALLOCATOR_H)
    return str(GENERATED_INCLUDE_DIRECTORY)


def openssl_prefixes() -> list[str]:
    return [prefix for prefix in OPENSSL_PREFIX_CANDIDATES if prefix and os.path.isdir(prefix)]


def extension_sources() -> list[str]:
    engine = sorted(
        path for path in glob.glob(f"{SOURCE_DIRECTORY}/*.cpp") if os.path.basename(path) not in WINDOWS_ONLY_SOURCES
    )
    return [*engine, SWIG_GENERATED_SOURCE]


class ParallelBuildExt(build_ext):
    """Compile on every core unless -j was given; the engine is ~55 translation units."""

    def finalize_options(self):
        super().finalize_options()
        if self.parallel is None:
            self.parallel = os.cpu_count() or 1


prefixes = openssl_prefixes()
setup(
    data_files=[("share/quickfix", glob.glob("spec/FIX*.xml"))],
    cmdclass={"build_ext": ParallelBuildExt},
    ext_modules=[
        Extension(
            "_quickfix",
            extension_sources(),
            include_dirs=[
                SOURCE_DIRECTORY,
                SWIG_DIRECTORY,
                PYTHON_DIRECTORY,
                write_generated_headers(),
                *(f"{prefix}/include" for prefix in prefixes),
            ],
            library_dirs=[f"{prefix}/lib" for prefix in prefixes],
            libraries=["ssl", "crypto"],
            define_macros=[("HAVE_SSL", "1")],
            extra_compile_args=EXTRA_COMPILE_ARGS,
        )
    ],
)
